#!/bin/bash

echo "=================================="
echo "Keycloak Client Configuration Check"
echo "=================================="
echo ""
echo "Please verify the following settings in your Keycloak Admin Console:"
echo "URL: http://192.168.1.117:8080/admin"
echo ""
echo "Navigate to: Realm 'rag_app' -> Clients -> 'fastapi-client'"
echo ""
echo "Required Settings:"
echo "=================="
echo "1. General Settings:"
echo "   - Client ID: fastapi-client"
echo "   - Name: FastAPI Client (or any name)"
echo "   - Enabled: ON"
echo ""
echo "2. Access Settings:"
echo "   - Root URL: http://localhost:3000"
echo "   - Valid redirect URIs:"
echo "     * http://localhost:3000/*"
echo "     * http://192.168.1.117:3000/*"
echo "   - Valid post logout redirect URIs:"
echo "     * http://localhost:3000/*"
echo "     * http://192.168.1.117:3000/*"
echo "   - Web origins:"
echo "     * http://localhost:3000"
echo "     * http://192.168.1.117:3000"
echo "     * +"
echo ""
echo "3. Capability Config:"
echo "   - Client authentication: OFF (Public client)"
echo "   - Authorization: OFF"
echo "   - Standard flow: ON"
echo "   - Direct access grants: ON"
echo "   - Implicit flow: OFF"
echo ""
echo "4. Advanced Settings:"
echo "   - Proof Key for Code Exchange Code Challenge Method: S256"
echo ""
echo "=================================="
echo "Current Frontend URLs:"
echo "Local: http://localhost:3000"
echo "Network: http://192.168.1.117:3000"
echo ""
echo "Testing the Keycloak endpoint..."
curl -s http://192.168.1.117:8080/realms/rag_app/.well-known/openid-configuration > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "✓ Keycloak is accessible at http://192.168.1.117:8080"
else
    echo "✗ Cannot reach Keycloak at http://192.168.1.117:8080"
fi
echo ""